-- 达梦数据库建表语句 - 元数据采集版本记录表
CREATE TABLE DATA_METADATA_COLLECTION_VERSION (
    ID VARCHAR(36) NOT NULL,
    COLLECTION_ID VARCHAR(36) NOT NULL,
    EXECUTION_ID VARCHAR(36),
    DATA_TYPE VARCHAR(50) NOT NULL,
    VERSION_NUMBER INTEGER,
    VERSION_DESCRIPTION VARCHAR(500),
    CHANGE_SUMMARY VARCHAR(1000),
    CHANGE_DETAILS CLOB,
    IS_LATEST NUMBER(1),
    CREATE_TIME TIMESTAMP,
    CREATE_BY VARCHAR(50),
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(50),
    STATUS INTEGER,
    PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE DATA_METADATA_COLLECTION_VERSION IS '元数据采集版本记录表';

-- 添加列注释
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.ID IS '主键ID';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.COLLECTION_ID IS '采集ID';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.EXECUTION_ID IS '执行ID';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.DATA_TYPE IS '数据类型：table_structure, field_info, quality_report, lineage_info';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.VERSION_NUMBER IS '版本号';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.VERSION_DESCRIPTION IS '版本描述';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.CHANGE_SUMMARY IS '变更摘要';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.CHANGE_DETAILS IS '变更详情（JSON格式）';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.IS_LATEST IS '是否为最新版本：1-是，0-否';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.CREATE_BY IS '创建人';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN DATA_METADATA_COLLECTION_VERSION.STATUS IS '状态：0-无效，1-有效';

-- 创建索引
CREATE INDEX IDX_MDCV_COLLECTION_ID ON DATA_METADATA_COLLECTION_VERSION (COLLECTION_ID);
CREATE INDEX IDX_MDCV_DATA_TYPE ON DATA_METADATA_COLLECTION_VERSION (DATA_TYPE);
CREATE INDEX IDX_MDCV_IS_LATEST ON DATA_METADATA_COLLECTION_VERSION (IS_LATEST); 