-- 达梦数据库建表语句 - 元数据版本变更日志表
CREATE TABLE DATA_METADATA_VERSION_CHANGE_LOG (
    ID VARCHAR(36) NOT NULL,
    VERSION_ID VARCHAR(36) NOT NULL,
    CHANGE_TYPE VARCHAR(50) NOT NULL,
    OBJECT_TYPE VARCHAR(50) NOT NULL,
    OBJECT_ID VARCHAR(36),
    OBJECT_NAME VARCHAR(200),
    OBJECT_PATH VARCHAR(500),
    BEFORE_VALUE CLOB,
    AFTER_VALUE CLOB,
    CHANGED_FIELDS CLOB,
    CHANGE_DESCRIPTION VARCHAR(1000),
    CHANGE_TIME TIMESTAMP,
    CHANGER_ID VARCHAR(36),
    CHANGER_NAME VARCHAR(100),
    CREATE_TIME TIMESTAMP,
    IS_DELETED INTEGER DEFAULT 0,
    PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE DATA_METADATA_VERSION_CHANGE_LOG IS '元数据版本变更日志表';

-- 添加列注释
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.ID IS '主键ID，使用UUID';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.VERSION_ID IS '版本ID';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CHANGE_TYPE IS '变更类型';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.OBJECT_TYPE IS '对象类型';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.OBJECT_ID IS '对象ID';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.OBJECT_NAME IS '对象名称';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.OBJECT_PATH IS '对象路径';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.BEFORE_VALUE IS '变更前值，使用JSON格式';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.AFTER_VALUE IS '变更后值，使用JSON格式';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CHANGED_FIELDS IS '变更字段，使用JSON格式';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CHANGE_DESCRIPTION IS '变更描述';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CHANGE_TIME IS '变更时间';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CHANGER_ID IS '变更者ID';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CHANGER_NAME IS '变更者名称';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DATA_METADATA_VERSION_CHANGE_LOG.IS_DELETED IS '是否删除：0-否，1-是';

-- 创建索引
CREATE INDEX IDX_MDVCL_VERSION_ID ON DATA_METADATA_VERSION_CHANGE_LOG (VERSION_ID);
CREATE INDEX IDX_MDVCL_OBJECT_ID ON DATA_METADATA_VERSION_CHANGE_LOG (OBJECT_ID);
CREATE INDEX IDX_MDVCL_CHANGE_TYPE ON DATA_METADATA_VERSION_CHANGE_LOG (CHANGE_TYPE);
CREATE INDEX IDX_MDVCL_OBJECT_TYPE ON DATA_METADATA_VERSION_CHANGE_LOG (OBJECT_TYPE);
CREATE INDEX IDX_MDVCL_CHANGE_TIME ON DATA_METADATA_VERSION_CHANGE_LOG (CHANGE_TIME); 