CREATE TABLE DATA_METADATA_QUALITY_REPORT (
    ID VARCHAR(64) NOT NULL,
    COLLECTION_ID VARCHAR(64),
    EXECUTION_ID VARCHAR(64),
    VERSION INTEGER,
    TABLE_NAME VARCHAR(128),
    TOTAL_ROWS BIGINT,
    VIOLATION_COUNT INTEGER,
    VIOLATION_DETAILS CLOB,
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
    UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
    IS_DELETED INTEGER DEFAULT 0,
    IS_LATEST INTEGER DEFAULT 1,
    CONSTRAINT PK_DATA_METADATA_QUALITY_REPORT PRIMARY KEY (ID)
);

CREATE INDEX IDX_QUALITY_REPORT_COLLECTION_ID ON DATA_METADATA_QUALITY_REPORT (COLLECTION_ID);
CREATE INDEX IDX_QUALITY_REPORT_EXECUTION_ID ON DATA_METADATA_QUALITY_REPORT (EXECUTION_ID);
CREATE INDEX IDX_QUALITY_REPORT_TABLE_NAME ON DATA_METADATA_QUALITY_REPORT (TABLE_NAME);
CREATE INDEX IDX_QUALITY_REPORT_VERSION ON DATA_METADATA_QUALITY_REPORT (VERSION);
CREATE INDEX IDX_QUALITY_REPORT_IS_LATEST ON DATA_METADATA_QUALITY_REPORT (IS_LATEST);
CREATE INDEX IDX_QUALITY_REPORT_IS_DELETED ON DATA_METADATA_QUALITY_REPORT (IS_DELETED);

ALTER TABLE DATA_METADATA_QUALITY_REPORT ADD CONSTRAINT CK_QUALITY_REPORT_IS_DELETED CHECK (IS_DELETED IN (0, 1));
ALTER TABLE DATA_METADATA_QUALITY_REPORT ADD CONSTRAINT CK_QUALITY_REPORT_IS_LATEST CHECK (IS_LATEST IN (0, 1));

CREATE SEQUENCE SEQ_METADATA_QUALITY_REPORT_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER TRG_METADATA_QUALITY_REPORT_ID
BEFORE INSERT ON DATA_METADATA_QUALITY_REPORT
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT 'QR' || TO_CHAR(SYSDATE, 'YYYYMMDD') || LPAD(SEQ_METADATA_QUALITY_REPORT_ID.NEXTVAL, 6, '0')
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_METADATA_QUALITY_REPORT_UPDATE
BEFORE UPDATE ON DATA_METADATA_QUALITY_REPORT
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYSDATE;
END;
/

COMMENT ON TABLE DATA_METADATA_QUALITY_REPORT IS '元数据质量报告表';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.ID IS '主键ID';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.COLLECTION_ID IS '采集任务ID';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.EXECUTION_ID IS '执行ID';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.VERSION IS '版本号';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.TABLE_NAME IS '表名';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.TOTAL_ROWS IS '总行数';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.VIOLATION_COUNT IS '违规数量';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.VIOLATION_DETAILS IS '违规详情（JSON格式）';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.IS_DELETED IS '是否删除（0-未删除，1-已删除）';
COMMENT ON COLUMN DATA_METADATA_QUALITY_REPORT.IS_LATEST IS '是否最新版本（0-否，1-是）';

CREATE OR REPLACE VIEW V_METADATA_QUALITY_REPORT_LATEST AS
SELECT *
FROM DATA_METADATA_QUALITY_REPORT
WHERE IS_LATEST = 1 AND IS_DELETED = 0;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_QUALITY_REPORT_VERSION(
    p_collection_id IN VARCHAR2,
    p_execution_id IN VARCHAR2
) AS
BEGIN
    UPDATE DATA_METADATA_QUALITY_REPORT
    SET IS_LATEST = 0
    WHERE COLLECTION_ID = p_collection_id
    AND EXECUTION_ID <> p_execution_id
    AND IS_LATEST = 1;
    
    COMMIT;
END;
/

CREATE OR REPLACE FUNCTION FUNC_GET_QUALITY_REPORT_MAX_VERSION(
    p_collection_id IN VARCHAR2
) RETURN NUMBER AS
    v_max_version NUMBER;
BEGIN
    SELECT COALESCE(MAX(VERSION), 0)
    INTO v_max_version
    FROM DATA_METADATA_QUALITY_REPORT
    WHERE COLLECTION_ID = p_collection_id
    AND IS_DELETED = 0;
    
    RETURN v_max_version;
END;
/

INSERT INTO DATA_METADATA_QUALITY_REPORT (
    ID, COLLECTION_ID, EXECUTION_ID, VERSION, TABLE_NAME,
    TOTAL_ROWS, VIOLATION_COUNT, VIOLATION_DETAILS,
    CREATE_TIME, UPDATE_TIME, IS_DELETED, IS_LATEST
) VALUES (
    'QR20230101000001', 'COL20230101000001', 'EXE20230101000001', 1, 'CUSTOMER',
    1000, 5, '{"null_values": 2, "duplicate_values": 3, "details": [{"column": "email", "error": "null_value", "count": 2}, {"column": "customer_id", "error": "duplicate_value", "count": 3}]}',
    SYSDATE, SYSDATE, 0, 1
);

INSERT INTO DATA_METADATA_QUALITY_REPORT (
    ID, COLLECTION_ID, EXECUTION_ID, VERSION, TABLE_NAME,
    TOTAL_ROWS, VIOLATION_COUNT, VIOLATION_DETAILS,
    CREATE_TIME, UPDATE_TIME, IS_DELETED, IS_LATEST
) VALUES (
    'QR20230101000002', 'COL20230101000001', 'EXE20230101000001', 1, 'ORDER',
    500, 2, '{"null_values": 1, "invalid_date": 1, "details": [{"column": "customer_id", "error": "null_value", "count": 1}, {"column": "order_date", "error": "invalid_date", "count": 1}]}',
    SYSDATE, SYSDATE, 0, 1
); 