-- 添加采集执行相关字段
ALTER TABLE METADATA_COLLECTION ADD LAST_EXECUTION_ID VARCHAR2(64);
ALTER TABLE METADATA_COLLECTION ADD LAST_EXECUTE_TIME TIMESTAMP;
ALTER TABLE METADATA_COLLECTION ADD EXECUTION_STATUS NUMBER(1) DEFAULT 0;
ALTER TABLE METADATA_COLLECTION ADD EXECUTION_MESSAGE VARCHAR2(512);

-- 添加字段注释
COMMENT ON COLUMN METADATA_COLLECTION.LAST_EXECUTION_ID IS '最后执行ID';
COMMENT ON COLUMN METADATA_COLLECTION.LAST_EXECUTE_TIME IS '最后执行时间';
COMMENT ON COLUMN METADATA_COLLECTION.EXECUTION_STATUS IS '执行状态(0-未执行 1-执行中 2-执行成功 3-执行失败)';
COMMENT ON COLUMN METADATA_COLLECTION.EXECUTION_MESSAGE IS '执行消息'; 