-- 加密规则表
CREATE TABLE IF NOT EXISTS `ds_encrypt_rule` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `datasource_id` varchar(32) NOT NULL COMMENT '数据源ID',
  `datasource_name` varchar(100) DEFAULT NULL COMMENT '数据源名称',
  `table_name` varchar(100) NOT NULL COMMENT '表名',
  `table_display_name` varchar(100) DEFAULT NULL COMMENT '表显示名',
  `field_name` varchar(100) NOT NULL COMMENT '字段名',
  `field_display_name` varchar(100) DEFAULT NULL COMMENT '字段显示名',
  `encrypt_type` varchar(32) NOT NULL COMMENT '加密类型: aes, sm4, md5, sha256, custom',
  `scenario_type` varchar(32) NOT NULL COMMENT '场景类型: email, phone, idcard, name, address, bank_card, custom',
  `is_custom_algorithm` tinyint(1) DEFAULT 0 COMMENT '是否使用自定义加密算法',
  `custom_algorithm_class` varchar(255) DEFAULT NULL COMMENT '自定义加密算法类名',
  `encrypt_key` varchar(128) DEFAULT NULL COMMENT '加密密钥',
  `status` varchar(20) NOT NULL DEFAULT 'enabled' COMMENT '状态: enabled, disabled',
  `priority` int DEFAULT 50 COMMENT '优先级',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
  PRIMARY KEY (`id`),
  INDEX `idx_datasource_table` (`datasource_id`, `table_name`),
  INDEX `idx_field` (`field_name`),
  INDEX `idx_status` (`status`),
  INDEX `idx_encrypt_type` (`encrypt_type`),
  INDEX `idx_scenario_type` (`scenario_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='加密规则表'; 